version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e8:05:79:32:a1:30:3a:23:26:56:9a:21:b5:35:93:a1"
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "SimpleCalc/SimpleCalc.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "SimpleCalc/SimpleCalc.csproj" }}
      - add_ssh_keys:
          fingerprints:
            - "SHA256:tR8dLiqNUyVz46CS1W9TS9z6SukWE0UCdwy96Mu+65M"
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
